# Site settings
title: Thinking Out Loud.
email: calos.colorado@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Unix, vim and life recipes for the end of the internet's golden era.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ccolorado.github.io/"
twitter_username: ccolorado
github_username:  ccolorado

# Build settings
markdown: kramdown
